### ISSUE TITLE
Gamepad works but still shows error: Gamepad #0 not found. Connect controller and press any button to continue.

### ISSUE THREAD

**Issue by js-d-coder** [donmccurdy/aframe-gamepad-controls#15]
Hi. Thanks a lot for this component.
I am using Windows 10 and Edge 41.16299.371.0 for testing this component (version 0.6.0)
My gamepad Red Gear works fine (can move around and click) but I am still getting this error in console:  

    Gamepad #0 not found. Connect controller and press any button to continue.

Besides this there is nothing harmful about this component in this case. Thanks again

**Comment by donmccurdy** [comment]
This project is no longer maintained. I recommend using `movement-controls` from [A-Frame Extras](https://github.com/donmccurdy/aframe-extras) instead.
