### ISSUE TITLE
How can I detect whether a gamepad is connected or not using this component?

### ISSUE THREAD

**Issue by js-d-coder** [donmccurdy/aframe-gamepad-controls#17]
Hi,  
I am using 0.6.0 version of this component and I am testing it on Windows 10 and Edge 41.16299.371.0 using Red Gear.  
I went through README.md and couldn't find a method or someway this component provides using which I can detect whether a gamepad is connected or not. Is there something I am missing? or do I have to use `navigator.getGamepads()` for this purpose?  
Thanks.

**Comment by donmccurdy** [comment]
Another option is `el.components['gamepad-controls'].getGamepad()`

**Comment by donmccurdy** [comment]
If you want to use alternate controls when a gamepad is not available, I suggest using `movement-controls` instead, which handles gamepads and other controls automatically: https://github.com/donmccurdy/aframe-extras/tree/master/src/controls

**Comment by js-d-coder** [comment]
Can `movement-controls` be used along side of `gamepad-controls` and `laser-controls` ? Currently, I use the later two...

**Comment by donmccurdy** [comment]
It automatically includes a different version of `gamepad-controls`, and cannot be used alongside this one. Using it with `laser-controls` should be fine.

**Comment by donmccurdy** [comment]
This project is no longer maintained. I recommend using `movement-controls` from [A-Frame Extras](https://github.com/donmccurdy/aframe-extras) instead.
