### ISSUE TITLE
when HMD of Windows Mixed Reality is connected, cannot do rotation by gamepad's joystick

### ISSUE THREAD

**Issue by js-d-coder** [donmccurdy/aframe-gamepad-controls#18]
Hi,  
I have been testing this component a lot recently, you must know from previous issues :-)  
 I am using Windows 10 and Edge 41.16299.371.0 for testing this component (version 0.6.0) along with HP's Window Mixed Reality HMD.
I wanted to confirm a behavior: when HMD of Windows Mixed Reality is connected, cannot do rotation by gamepad's joystick. Of course this is desired behavior for users. My question is: Is it expected behavior of this component? can I rely on this behavior reliably?  
Thanks a lot for this component, very useful.

**Comment by donmccurdy** [comment]
This component is really meant to be used alone; it doesn't do anything clever when an HMD shows up, but I'm glad it's working as expected. For something tested and meant for "responsive" adjustment to HMDs, mobile devices, and regular PCs with WASD or gamepads, see `movement-controls` in aframe-extras.

**Comment by js-d-coder** [comment]
Quick question, is it okay to use `laser-controls` for Windows Mixed Reality along side `movement-controls`?

```
<a-entity laser-controls="hand: left" line="color: blue; opacity:0.5" ></a-entity>
<a-entity laser-controls="hand: right" line="color: blue; opacity:0.5" ></a-entity>
```

**Comment by donmccurdy** [comment]
This should be fine, yes. I suggest putting the controls inside the camera rig but not inside the camera.

**Comment by donmccurdy** [comment]
This project is no longer maintained. I recommend using `movement-controls` from [A-Frame Extras](https://github.com/donmccurdy/aframe-extras) instead.
