### ISSUE TITLE
invertedEnabled flag

### ISSUE THREAD

**Issue by andygill** [donmccurdy/aframe-gamepad-controls#8]
Some old-timers like myself like to play controller games with the lookVector.y reversed. I'll send a pull request after I've tested my changes. I propose adding 

```
invertedEnabled:   { default: false },
```

to the `schema`, and the line

```
if (this.data.invertedEnabled) lookVector.y = -lookVector.y;
```

just after `lookVector` is updated.

**Comment by donmccurdy** [comment]
Sounds good to me! Let's call the option `invertAxisY`.

**Comment by andygill** [comment]
Sent pull, with `invertAxisY` naming.
